name: Gatsby CI

on:
  push:
    branches:
      - master
  schedule:
    # Cron schedule using UTC time
    - cron: "0 10 * * *"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test
        env:
          GRAPHCMS_ENDPOINT: ${{ secrets.GRAPHCMS_ENDPOINT }}
        run: |
          npm run test
      - name: Build and Deploy Gatsby
        uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GRAPHCMS_ENDPOINT: ${{ secrets.GRAPHCMS_ENDPOINT }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: deploy
