name: Gatsby CI

on:
  push:
    branches:
      - master
  schedule:
    # Cron schedule using UTC time
    - cron: "0 10 * * *"

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
        node:
          - 15

    runs-on: ${{ matrix.os }}

    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Configures the node version used on GitHub-hosted runners
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
      - name: Test
        env:
          GRAPHCMS_ENDPOINT: ${{ secrets.GRAPHCMS_ENDPOINT }}
          GRAPHCMS_TOKEN: ${{ secrets.GRAPHCMS_TOKEN }}
        run: |
          npm run test
      - name: Build and Deploy Gatsby
        uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GRAPHCMS_ENDPOINT: ${{ secrets.GRAPHCMS_ENDPOINT }}
          GRAPHCMS_TOKEN: ${{ secrets.GRAPHCMS_TOKEN }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: deploy
