name: Gatsby CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Test
        run: |
          npm run test
      - name: Build and Deploy Gatsby
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: deploy
