name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node: ${{ matrix.node }}
      - name: Clean install
        run: |
          npm ci
        env:
          CI: true
      - name: Copy to public folder
        run: |
          cp README.md public/README.md
      - name: Build, test, and deploy
        run: |
          npm run test
          npm run deploy
